# Generated by Django 5.0.6 on 2024-07-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="first_name",
            new_name="firstName",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="last_name",
            new_name="lastName",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="user_id",
            new_name="userId",
        ),
    ]
