# Generated by Django 5.0.6 on 2024-07-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_organisation_delete_customuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="userId",
        ),
    ]
